### PR TITLE
Implement SpotifyAPI Playlist Retrieval based on Category

### LINKED ISSUE #12: Feature: integrate Spotify API for playlists retrieval
### Description:
Integrate the Spotify API into the Playtify app to fetch playlists from a specific category (e.g., "Pop," "Rock," "Chill"). This integration will allow the app to access and display Spotify playlists within the chosen category.

### Tips for the issue:
- Set up Spotify API integration in the Playtify project
- Implement a function to retrieve playlists from a specified category

### To do:
- [x] Ask us to assign the issue
- [x]  Once the issue is assigned, you can start working on it
- [x]  Create a PR

### Resources:
- [pub.dev/spotify_sdk](https://pub.dev/packages/spotify_sdk)

### Note:
The task is **assigned to contributors on a first-come, first-serve basis**, and the contributor has to **report progress every 3 days** to ensure active development on the tasks. If you need any help feel free to tag and message

### PR DESCRIPTION
**Pull request by RitwikSingh28**
Resolve #12 

## Problem Statement
This PR addresses the integration of the `SpotifyAPI` into the Playtify app, enabling the retrieval of playlists from specific categories, such as "Pop," "Rock," or "Chill." This integration enhances the app's functionality by granting access to and displaying Spotify playlists within the selected category.

## Changes Made

* Configured Spotify API integration within the Playtify project, ensuring seamless communication with the Spotify platform.
* Implemented functions responsible for fetching playlists based on user-specified categories. The function efficiently interacts with the Spotify API to retrieve and present the desired playlist data.

## Approach

* Created `SpotifyService` class - Responsible for **authorizing, and managing the tokens** for a user-session
* Created `utils.dart` file - Responsible for storing the **Configuration** details, such as `url`, `client_id`, `client_secret` etc.
* Added `fetchCategories()` method - Responsible for **retrieving all `category_id`'s** on Spotify, so that the user can select one of them and get playlists based on that category using `getCategoryPlaylist()` method

## Important Note

* The CLIENT_ID and CLIENT_SECRET required for Spotify API access have been **securely stored in the project's .env file** and are accessed using the dotenv package. As a result, **contributors won't have direct access to these credentials**.
* To facilitate your involvement and contribution to Spotify API-related tasks, please **provide your email address associated with your Spotify account**. This will allow the ownership of the Spotify application to be transferred to you.
* Once you have ownership, you will be able to obtain the necessary CLIENT_ID and CLIENT_SECRET from Spotify. You should then create a .env file in the project directory, specifying the credentials as follows:
```
CLIENT_ID='<your-client-id>'
CLIENT_SECRET='<your-client-secret>'
```

### CODE REVIEW

**Comment by RitwikSingh28** [comment]
@dk-a-dev Please review the PR, and let me know if anything needs to be cleared up or modified.

Thank you!

**Comment by dk-a-dev** [comment]
@RitwikSingh28 since i need to test the app, can u add my gmail as a contributor to spotify dev portal for this project, no need of transferring ownership for now just give me access so that I can generate client id and token to review app

**Comment by RitwikSingh28** [comment]
Sure @dk-a-dev 
Please provide me your email address and I will add you as a user too. 

Although please keep in mind that I have written the logic for the backend, and **have not integrated it with the application**.
In case you want me to provide snapshots of the results of the function calls, I can add them to the PR description.

**Comment by dk-a-dev** [comment]
Have u added any way a user can authenticate

> Sure @dk-a-dev Please provide me your email address and I will add you as a user too.
> 
> Although please keep in mind that I have written the logic for the backend, and **have not integrated it with the application**. In case you want me to provide snapshots of the results of the function calls, I can add them to the PR description.

yup here it is dev.keshwani345@gmail.com
yup plz add snapshots, once I review the backend I will create an issue to make the auth screen and also integrate existing functions with frontend of app

**Comment by RitwikSingh28** [comment]
The Spotify API Authorization will take care of the login aspect from Spotify account. 
I will add unit tests in the subsequent commits to this PR, so that you may see the tests yourself.

Since I am travelling, I will be able to update it by tomorrow evening.

**Comment by RitwikSingh28** [comment]
@dk-a-dev 
It seems that User Management feature of the Spotify SDK will allow you to only add users that can authenticate directly. It won't add other people as collaborators for the project.

Since I have created the project using my own spotify-account, let me provide you the steps that will let you have your own API keys. 

# Steps
1. Create a Web API Project, and add `Project Name` and `Project Description`
2. Go to `Settings`
3. There you will find your `CLIENT_ID` and `CLIENT_SECRET` which you will need to store in `.env` file, and using `flutter_dotenv` package, access it in your code base
4. Scroll to the bottom of `Basic Information` tab, and click on `Edit`
5. Add the following `Redirect URI`: `com.example.playtify://`
6. In `Android Packages`, add the `Package Name`: `com.example.playtify` and fill in the `SHA1` fingerprint signature of the app
7. Click on `Save`, and you're done

I am adding the Unit Tests in the meanwhile, and will push them in the subsequent commits. I urge you to follow the above steps and try to work it out. In case you feel stuck, please reach out to me.

**Comment by dk-a-dev** [comment]
@shubhbansal9 can u please review this one I am having some trouble with my build gradle, so I am unable to get SHA-1 retrieve the fingerprint

**Review by dk-a-dev — APPROVED** [review]
Good Job

**Pull request merged**
